// Package matcher maps detected services to CPEs and matches them against the
// local CVE database. It is the bridge between fingerprinting (what we detected)
// and vulnerability intelligence (what's known about those products).
//
// Design:
//   - CPE matching uses the CPE 2.3 URI format generated by the fingerprint package.
//   - When an exact version CPE exists, we look up CVEs for that specific version.
//   - We also look up CVEs for the product line (wildcard version) to catch
//     vulnerabilities that existed before the detected version was superseded.
//   - KEV and EPSS data are joined on-the-fly to enrich findings.
package matcher

import (
	"context"
	"fmt"
	"strings"

	"github.com/evilhunter/surfaceguard/internal/database"
	"github.com/evilhunter/surfaceguard/pkg/models"
)

// Matcher handles CPE-to-CVE matching logic.
type Matcher struct {
	db database.Database
}

// New creates a new Matcher backed by the given database.
func New(db database.Database) *Matcher {
	return &Matcher{db: db}
}

// MatchPort looks up all CVEs for a given port's detected CPEs. It returns
// a slice of Findings — each Finding is one CVE matched to one CPE.
func (m *Matcher) MatchPort(ctx context.Context, host, ip string, port models.Port) []models.Finding {
	if len(port.CPEs) == 0 {
		return nil
	}

	var findings []models.Finding

	for _, cpe := range port.CPEs {
		portFindings := m.matchCPE(ctx, host, ip, port, cpe)
		findings = append(findings, portFindings...)
	}

	return findings
}

// matchCPE looks up CVEs for a single CPE entry.
func (m *Matcher) matchCPE(ctx context.Context, host, ip string, port models.Port, cpe models.CPE) []models.Finding {
	var findings []models.Finding

	// First: look up the CPE in the database.
	dbCPEs, err := m.db.CPE().FindByCPE23URI(ctx, cpe.CPE23URI)
	if err != nil {
		return nil
	}

	// If no exact match, try with wildcard version.
	if len(dbCPEs) == 0 {
		wildcardCPE := cpe
		wildcardCPE.Version = "*"
		wildcardCPE.CPE23URI = wildcardCPE.String()
		dbCPEs, _ = m.db.CPE().FindByCPE23URI(ctx, wildcardCPE.CPE23URI)
	}

	// If still no match, try vendor+product wildcard version.
	if len(dbCPEs) == 0 && cpe.Version != "*" {
		dbCPEs, _ = m.db.CPE().FindByProduct(ctx, cpe.Vendor, cpe.Product, cpe.Version)
	}

	// If still no match, look up CVEs directly by vendor and product name.
	if len(dbCPEs) == 0 {
		dbCVEs, _ := m.db.CVE().SearchByProduct(ctx, cpe.Vendor, cpe.Product)
		for _, dbCVE := range dbCVEs {
			finding := m.buildFinding(ctx, host, ip, port, cpe, dbCVE)
			findings = append(findings, finding)
		}
		return findings
	}

	// Look up CVEs for each matched CPE.
	for _, dbCPE := range dbCPEs {
		// Look up CVEs by CPE ID.
		dbCVEs, err := m.db.CVE().FindByCPEID(ctx, dbCPE.ID)
		if err != nil {
			continue
		}

		for _, dbCVE := range dbCVEs {
			// Enrich with KEV and EPSS data.
			finding := m.buildFinding(ctx, host, ip, port, cpe, dbCVE)
			findings = append(findings, finding)
		}
	}

	return findings
}

// buildFinding creates a Finding from a matched CVE, enriching with KEV and EPSS.
func (m *Matcher) buildFinding(ctx context.Context, host, ip string, port models.Port, cpe models.CPE, dbCVE database.DBCVE) models.Finding {
	// Enrich with KEV status.
	var dbKEV *database.DBKEV
	kev, err := m.db.KEV().GetByCVEID(ctx, dbCVE.CVEID)
	if err == nil {
		dbKEV = kev
	}

	// Enrich with EPSS score.
	var dbEpss *database.DBEpss
	epss, err := m.db.EPSS().GetByCVEID(ctx, dbCVE.CVEID)
	if err == nil {
		dbEpss = epss
	}

	// Convert to domain model.
	domainCVE := database.ToDomainCVE(&dbCVE, dbKEV, dbEpss)

	return models.Finding{
		Host:       host,
		IP:         ip,
		Port:       port,
		CVE:        domainCVE,
		MatchedCPE: cpe,
	}
}

// MatchAllPorts runs MatchPort for every open port and returns aggregated findings.
func (m *Matcher) MatchAllPorts(ctx context.Context, host, ip string, ports []models.Port) []models.Finding {
	var allFindings []models.Finding
	for _, port := range ports {
		findings := m.MatchPort(ctx, host, ip, port)
		allFindings = append(allFindings, findings...)
	}
	return allFindings
}

// ============================================================================
// CPE Utility Functions
// ============================================================================

// NormalizeCPEVendor normalises vendor names for CPE matching.
// CPE vendors are always lowercase; this function strips common prefixes
// and normalises separators.
func NormalizeCPEVendor(vendor string) string {
	vendor = strings.ToLower(strings.TrimSpace(vendor))
	// Strip "the " prefix which isn't part of the CPE vendor name.
	vendor = strings.TrimPrefix(vendor, "the ")
	// If there are still spaces, just take the first word.
	if strings.Contains(vendor, " ") {
		parts := strings.Fields(vendor)
		return parts[0]
	}
	return vendor
}

// NormalizeCPEProduct normalises product names for CPE matching.
func NormalizeCPEProduct(product string) string {
	product = strings.ToLower(strings.TrimSpace(product))
	// Normalise spaces to underscores.
	product = strings.ReplaceAll(product, " ", "_")
	return product
}

// CPEKey generates a composite key for a CPE URI for deduplication.
func CPEKey(uri string) string {
	return strings.ToLower(strings.TrimSpace(uri))
}

// CVEAffectedVersions returns a human-readable string describing affected
// versions for display in reports. Currently a placeholder for future
// version range logic.
func CVEAffectedVersions(cve models.CVE) string {
	if cve.CPE23URI != "" {
		parts := strings.Split(cve.CPE23URI, ":")
		if len(parts) >= 6 {
			return parts[5] // version part (indices: 0=cpe, 1=2.3, 2=part, 3=vendor, 4=product, 5=version)
		}
	}
	return "unknown"
}

// FilterByCVSS filters findings to only those meeting the minimum CVSS threshold.
func FilterByCVSS(findings []models.Finding, threshold float64) []models.Finding {
	if threshold <= 0 {
		return findings
	}
	var filtered []models.Finding
	for _, f := range findings {
		if f.CVE.CVSSv3 != nil && *f.CVE.CVSSv3 >= threshold {
			filtered = append(filtered, f)
		} else if f.CVE.CVSSv2 != nil && *f.CVE.CVSSv2 >= threshold {
			filtered = append(filtered, f)
		}
	}
	return filtered
}

// DeduplicateFindings removes duplicate findings based on CVE ID + CPE URI.
func DeduplicateFindings(findings []models.Finding) []models.Finding {
	seen := make(map[string]bool)
	var unique []models.Finding

	for _, f := range findings {
		key := fmt.Sprintf("%s|%s", f.CVE.ID, f.MatchedCPE.CPE23URI)
		if seen[key] {
			continue
		}
		seen[key] = true
		unique = append(unique, f)
	}

	return unique
}

// SortFindings sorts findings by severity (CRITICAL first), then by CVSSv3 desc.
func SortFindings(findings []models.Finding) {
	for i := 0; i < len(findings); i++ {
		for j := i + 1; j < len(findings); j++ {
			swap := false
			// Higher severity first.
			if severityRank(findings[i].CVE.Severity) < severityRank(findings[j].CVE.Severity) {
				swap = true
			} else if severityRank(findings[i].CVE.Severity) == severityRank(findings[j].CVE.Severity) {
				// Higher CVSSv3 first.
				ci, cj := 0.0, 0.0
				if findings[i].CVE.CVSSv3 != nil {
					ci = *findings[i].CVE.CVSSv3
				}
				if findings[j].CVE.CVSSv3 != nil {
					cj = *findings[j].CVE.CVSSv3
				}
				if ci < cj {
					swap = true
				}
			}
			if swap {
				findings[i], findings[j] = findings[j], findings[i]
			}
		}
	}
}

func severityRank(severity string) int {
	switch severity {
	case "CRITICAL":
		return 4
	case "HIGH":
		return 3
	case "MEDIUM":
		return 2
	case "LOW":
		return 1
	default:
		return 0
	}
}
