// Package matcher maps detected services to CPEs and matches them against the
// local CVE database. It is the bridge between fingerprinting (what we detected)
// and vulnerability intelligence (what's known about those products).
//
// Design:
//   - CPE matching uses the CPE 2.3 URI format generated by the fingerprint package.
//   - Matching requires an exact CPE URI match in the database. No wildcard version
//     matching is performed — unmatched versions return no findings.
//   - No vendor-agnostic fallback is performed — CPE matching requires a known vendor.
//   - KEV and EPSS data are joined on-the-fly to enrich findings.
//   - Phase 2 adds version intelligence: NVD range validation, DB CPE version
//     comparison, and nearby version matching. Findings where the detected
//     version does not match the CVE's affected range are filtered out.
package matcher

import (
	"context"
	"fmt"
	"log/slog"
	"strings"

	"github.com/evilhunter/surfaceguard/internal/database"
	"github.com/evilhunter/surfaceguard/pkg/models"
	"github.com/evilhunter/surfaceguard/pkg/version"
)

// Options configures the Matcher's fallback behaviour.
// Note: Phase 1 FP fixes disabled wildcard version matching and vendor-agnostic
// fallback. MinConfidenceForFallback is retained for future use but currently
// unused as no fallback paths remain.
type Options struct {
	// MinConfidenceForFallback is retained for API compatibility.
	// Phase 1: no fallback paths currently use this value.
	MinConfidenceForFallback int
}

// Matcher handles CPE-to-CVE matching logic.
type Matcher struct {
	db       database.Database
	opts     Options
}

// New creates a new Matcher backed by the given database with default options.
func New(db database.Database) *Matcher {
	return NewWithOptions(db, Options{})
}

// NewWithOptions creates a new Matcher backed by the given database and options.
func NewWithOptions(db database.Database, opts Options) *Matcher {
	return &Matcher{db: db, opts: opts}
}

// MatchPort looks up all CVEs for a given port's detected CPEs. It returns
// a slice of Findings — each Finding is one CVE matched to one CPE.
// Findings are annotated with MatchConfidence, MatchType, and MatchEvidence.
func (m *Matcher) MatchPort(ctx context.Context, host, ip string, port models.Port) []models.Finding {
	if len(port.CPEs) == 0 {
		return nil
	}

	// Capture the fingerprint confidence from the port so the matcher
	// can use it to gate fallback behaviour.
	conf := port.Confidence
	if conf < 0 {
		conf = 0
	}
	if conf > 100 {
		conf = 100
	}

	var findings []models.Finding

	for _, cpe := range port.CPEs {
		portFindings := m.matchCPE(ctx, host, ip, port, cpe, conf)
		findings = append(findings, portFindings...)
	}

	return findings
}

// matchCPE looks up CVEs for a single CPE entry.
// conf is the fingerprint confidence (0-100) from the port detection.
func (m *Matcher) matchCPE(ctx context.Context, host, ip string, port models.Port, cpe models.CPE, conf int) []models.Finding {
	// Phase 1: Exact CPE URI lookup (no wildcard fallback).
	dbCPEs, err := m.db.CPE().FindByCPE23URI(ctx, cpe.CPE23URI)
	if err != nil {
		return nil
	}

	detectedVer := port.Version

	if len(dbCPEs) > 0 {
		// Exact CPE match found. Run version intelligence against each matched CPE.
		return m.matchWithExactCPE(ctx, host, ip, port, cpe, dbCPEs, conf, detectedVer)
	}

	// No exact CPE match. Phase 2: try nearby version matching.
	if detectedVer != "" && cpe.Vendor != "*" && cpe.Product != "*" {
		return m.matchNearbyVersions(ctx, host, ip, port, cpe, conf, detectedVer)
	}

	slog.Debug("exact CPE not found in database — no match",
		"cpe_uri", cpe.CPE23URI,
		"vendor", cpe.Vendor,
		"product", cpe.Product,
		"version", cpe.Version,
	)
	return nil
}

// matchWithExactCPE processes an exact CPE match through version intelligence.
// It validates each CVE against the detected version and filters out
// findings where the version is confirmed not affected.
func (m *Matcher) matchWithExactCPE(ctx context.Context, host, ip string, port models.Port, cpe models.CPE, dbCPEs []database.DBCPE, conf int, detectedVer string) []models.Finding {
	var findings []models.Finding

	for _, dbCPE := range dbCPEs {
		dbCVEs, err := m.db.CVE().FindByCPEID(ctx, dbCPE.ID)
		if err != nil {
			continue
		}
		for _, dbCVE := range dbCVEs {
			finding := m.buildFinding(ctx, host, ip, port, cpe, dbCVE, conf, detectedVer, &dbCPE)
			// Phase 2: filter out findings confirmed not affected.
			if shouldSuppressFinding(finding) {
				continue
			}
			findings = append(findings, finding)
		}
	}

	return findings
}

// matchNearbyVersions attempts to find CPEs with the same vendor+product
// in the same major.minor version range as the detected version.
// This re-enables detection for products where the exact version CPE is
// not in the database, but a nearby version CPE exists — without the
// false-positive risk of wildcard matching across all versions.
func (m *Matcher) matchNearbyVersions(ctx context.Context, host, ip string, port models.Port, cpe models.CPE, conf int, detectedVer string) []models.Finding {
	nearbyCPEs, err := m.db.CPE().FindNearbyVersions(ctx, cpe.Vendor, cpe.Product, detectedVer, 5)
	if err != nil {
		slog.Warn("nearby version search failed",
			"vendor", cpe.Vendor, "product", cpe.Product,
			"version", detectedVer, "error", err,
		)
		return nil
	}
	if len(nearbyCPEs) == 0 {
		slog.Debug("no nearby versions found for detected software",
			"vendor", cpe.Vendor, "product", cpe.Product,
			"version", detectedVer,
		)
		return nil
	}

	parsedDetected := version.Parse(detectedVer)
	if parsedDetected.Unknown || parsedDetected.Wildcard {
		return nil
	}

	slog.Debug("found nearby CPE versions",
		"vendor", cpe.Vendor, "product", cpe.Product,
		"detected_version", detectedVer,
		"nearby_count", len(nearbyCPEs),
	)

	var findings []models.Finding
	for _, dbCPE := range nearbyCPEs {
		// Verify the DB CPE version is in the same major.minor family.
		dbVer := version.Parse(dbCPE.Version)
		if !version.IsNearbyVersion(parsedDetected, dbVer) {
			continue
		}

		dbCVEs, err := m.db.CVE().FindByCPEID(ctx, dbCPE.ID)
		if err != nil {
			continue
		}
		for _, dbCVE := range dbCVEs {
			finding := m.buildFinding(ctx, host, ip, port, cpe, dbCVE, conf, detectedVer, &dbCPE)
			// Mark as nearby version match and annotate.
			finding.MatchType = "nearby_version"
			finding.MatchedCPE = cpe
			finding.MatchedCPE.Version = dbCPE.Version
			finding.MatchedCPE.CPE23URI = dbCPE.CPE23URI
			if finding.MatchEvidence == "" {
				finding.MatchEvidence = fmt.Sprintf(
					"Detected Version: %s  DB CPE Version: %s  Match: Nearby Version (same major.minor)",
					detectedVer, dbCPE.Version)
			}

			// Apply same version validation filtering as exact matches.
			if shouldSuppressFinding(finding) {
				continue
			}
			findings = append(findings, finding)
		}
	}

	if len(findings) == 0 {
		slog.Debug("nearby versions found but all CVEs filtered out by version validation",
			"vendor", cpe.Vendor, "product", cpe.Product,
			"detected_version", detectedVer,
			"nearby_count", len(nearbyCPEs),
		)
	}

	return findings
}

// shouldSuppressFinding returns true if the finding should be suppressed
// based on version validation. We suppress findings where:
//   - NVD version range validation explicitly says "not_affected"
//   - DB CPE version is known and detected version is older (unlikely fix)
//
// We do NOT suppress "unknown" or "affected" findings.
func shouldSuppressFinding(f models.Finding) bool {
	if f.VersionValidation == "not_affected" {
		return true
	}
	return false
}

// buildFinding creates a Finding from a matched CVE, enriching with KEV, EPSS,
// and NVD version range validation. Phase 2 adds DB CPE version comparison
// and the VersionMatchResult classification.
func (m *Matcher) buildFinding(ctx context.Context, host, ip string, port models.Port, cpe models.CPE, dbCVE database.DBCVE, conf int, detectedVer string, dbCPE *database.DBCPE) models.Finding {
	// Enrich with KEV status.
	var dbKEV *database.DBKEV
	kev, err := m.db.KEV().GetByCVEID(ctx, dbCVE.CVEID)
	if err == nil {
		dbKEV = kev
	}

	// Enrich with EPSS score.
	var dbEpss *database.DBEpss
	epss, err := m.db.EPSS().GetByCVEID(ctx, dbCVE.CVEID)
	if err == nil {
		dbEpss = epss
	}

	// Convert to domain model (includes version range fields).
	domainCVE := database.ToDomainCVE(&dbCVE, dbKEV, dbEpss)

	// ============================================================================
	// NVD Version Range Validation
	// ============================================================================
	nvdRange := version.Range{
		StartIncluding: dbCVE.VersionStartIncluding,
		StartExcluding: dbCVE.VersionStartExcluding,
		EndIncluding:   dbCVE.VersionEndIncluding,
		EndExcluding:   dbCVE.VersionEndExcluding,
	}

	finding := models.Finding{
		Host:            host,
		IP:              ip,
		Port:            port,
		CVE:             domainCVE,
		MatchedCPE:      cpe,
		MatchConfidence: conf,
	}

	// Version intelligence: determine how the detected version relates to this CVE.
	if detectedVer == "" {
		// No version detected — cannot validate.
		finding.VersionMatchResult = "unknown_version"
		return finding
	}

	finding.DetectedVersion = detectedVer
	parsedDetected := version.Parse(detectedVer)

	// Phase 2: Check 1 — NVD version range validation (most authoritative).
	if nvdRange.StartIncluding != nil || nvdRange.StartExcluding != nil ||
		nvdRange.EndIncluding != nil || nvdRange.EndExcluding != nil {

		finding.AffectedVersionRange = nvdRange.String()
		result := nvdRange.Validate(parsedDetected)

		switch result {
		case 1:
			finding.VersionValidation = "affected"
			finding.VersionMatchResult = "version_range_match"
			if conf < 100 {
				finding.MatchConfidence = conf + 5
				if finding.MatchConfidence > 100 {
					finding.MatchConfidence = 100
				}
			}
			slog.Debug("version confirmed affected by NVD range",
				"cve", dbCVE.CVEID,
				"detected", detectedVer,
				"range", nvdRange.String(),
			)
		case -1:
			finding.VersionValidation = "not_affected"
			finding.VersionMatchResult = "version_mismatch"
			finding.MatchEvidence = fmt.Sprintf(
				"Detected Version: %s  Affected Range: %s  Validation: Not Affected",
				detectedVer, nvdRange.String())
			slog.Debug("version outside NVD affected range — suppressing",
				"cve", dbCVE.CVEID,
				"detected", detectedVer,
				"range", nvdRange.String(),
			)
		case 0:
			finding.VersionValidation = "unknown"
			finding.VersionMatchResult = "unknown_version"
			finding.MatchEvidence = fmt.Sprintf(
				"Detected Version: %s  Affected Range: %s  Validation: Unknown",
				detectedVer, nvdRange.String())
		}

		return finding
	}

	// Phase 2: Check 2 — No NVD range. Compare detected version against DB CPE version.
	if dbCPE != nil && dbCPE.Version != "" && dbCPE.Version != "*" {
		dbParsed := version.Parse(dbCPE.Version)
		if !dbParsed.Unknown && !dbParsed.Wildcard && !parsedDetected.Unknown && !parsedDetected.Wildcard {
			cmp := version.CompareBase(parsedDetected, dbParsed)

			// Same version = exact version match.
			if version.Compare(parsedDetected, dbParsed) == 0 {
				finding.VersionMatchResult = "exact_version"
				finding.VersionValidation = "affected"
				slog.Debug("exact version match against DB CPE",
					"cve", dbCVE.CVEID,
					"detected", detectedVer,
					"db_version", dbCPE.Version,
				)
				return finding
			}

			// Same major.minor = DB CPE version is a nearby reference.
			if version.IsNearbyVersion(parsedDetected, dbParsed) {
				finding.VersionMatchResult = "db_version_match"
				finding.VersionValidation = "affected"
				finding.MatchEvidence = fmt.Sprintf(
					"Detected Version: %s  DB CPE Version: %s  Match: Compatible (same major.minor)",
					detectedVer, dbCPE.Version)
				slog.Debug("detected version compatible with DB CPE version",
					"cve", dbCVE.CVEID,
					"detected", detectedVer,
					"db_version", dbCPE.Version,
				)
				return finding
			}

			// Different version family — likely a false positive.
			if cmp < 0 || cmp > 0 {
				finding.VersionMatchResult = "version_mismatch"
				finding.VersionValidation = "not_affected"
				finding.MatchEvidence = fmt.Sprintf(
					"Detected Version: %s  DB CPE Version: %s  Validation: Different version family (major.minor mismatch)",
					detectedVer, dbCPE.Version)
				slog.Debug("detected version mismatches DB CPE version — suppressing",
					"cve", dbCVE.CVEID,
					"detected", detectedVer,
					"db_version", dbCPE.Version,
				)
				return finding
			}
		}
	}

	// No version intelligence available — classification as unknown.
	finding.VersionMatchResult = "unknown_version"
	return finding
}

// MatchAllPorts runs MatchPort for every open port and returns aggregated findings.
func (m *Matcher) MatchAllPorts(ctx context.Context, host, ip string, ports []models.Port) []models.Finding {
	var allFindings []models.Finding
	for _, port := range ports {
		findings := m.MatchPort(ctx, host, ip, port)
		allFindings = append(allFindings, findings...)
	}
	return allFindings
}

// ============================================================================
// CPE Utility Functions
// ============================================================================

// NormalizeCPEVendor normalises vendor names for CPE matching.
// CPE vendors are always lowercase; this function strips common prefixes
// and normalises separators.
func NormalizeCPEVendor(vendor string) string {
	vendor = strings.ToLower(strings.TrimSpace(vendor))
	// Strip "the " prefix which isn't part of the CPE vendor name.
	vendor = strings.TrimPrefix(vendor, "the ")
	// If there are still spaces, just take the first word.
	if strings.Contains(vendor, " ") {
		parts := strings.Fields(vendor)
		return parts[0]
	}
	return vendor
}

// NormalizeCPEProduct normalises product names for CPE matching.
func NormalizeCPEProduct(product string) string {
	product = strings.ToLower(strings.TrimSpace(product))
	// Normalise spaces to underscores.
	product = strings.ReplaceAll(product, " ", "_")
	return product
}

// CPEKey generates a composite key for a CPE URI for deduplication.
func CPEKey(uri string) string {
	return strings.ToLower(strings.TrimSpace(uri))
}

// CVEAffectedVersions returns a human-readable string describing affected
// versions for display in reports.
func CVEAffectedVersions(cve models.CVE) string {
	if cve.CPE23URI != "" {
		parts := strings.Split(cve.CPE23URI, ":")
		if len(parts) >= 6 {
			return parts[5] // version part (indices: 0=cpe, 1=2.3, 2=part, 3=vendor, 4=product, 5=version)
		}
	}
	return "unknown"
}

// FilterByCVSS filters findings to only those meeting the minimum CVSS threshold.
func FilterByCVSS(findings []models.Finding, threshold float64) []models.Finding {
	if threshold <= 0 {
		return findings
	}
	var filtered []models.Finding
	for _, f := range findings {
		if f.CVE.CVSSv3 != nil && *f.CVE.CVSSv3 >= threshold {
			filtered = append(filtered, f)
		} else if f.CVE.CVSSv2 != nil && *f.CVE.CVSSv2 >= threshold {
			filtered = append(filtered, f)
		}
	}
	return filtered
}

// DeduplicateFindings removes duplicate findings based on CVE ID + CPE URI.
func DeduplicateFindings(findings []models.Finding) []models.Finding {
	seen := make(map[string]bool)
	var unique []models.Finding

	for _, f := range findings {
		key := fmt.Sprintf("%s|%s", f.CVE.ID, f.MatchedCPE.CPE23URI)
		if seen[key] {
			continue
		}
		seen[key] = true
		unique = append(unique, f)
	}

	return unique
}

// SortFindings sorts findings by severity (CRITICAL first), then by CVSSv3 desc.
func SortFindings(findings []models.Finding) {
	for i := 0; i < len(findings); i++ {
		for j := i + 1; j < len(findings); j++ {
			swap := false
			// Higher severity first.
			if severityRank(findings[i].CVE.Severity) < severityRank(findings[j].CVE.Severity) {
				swap = true
			} else if severityRank(findings[i].CVE.Severity) == severityRank(findings[j].CVE.Severity) {
				// Higher CVSSv3 first.
				ci, cj := 0.0, 0.0
				if findings[i].CVE.CVSSv3 != nil {
					ci = *findings[i].CVE.CVSSv3
				}
				if findings[j].CVE.CVSSv3 != nil {
					cj = *findings[j].CVE.CVSSv3
				}
				if ci < cj {
					swap = true
				}
			}
			if swap {
				findings[i], findings[j] = findings[j], findings[i]
			}
		}
	}
}

func severityRank(severity string) int {
	switch severity {
	case "CRITICAL":
		return 4
	case "HIGH":
		return 3
	case "MEDIUM":
		return 2
	case "LOW":
		return 1
	default:
		return 0
	}
}
